# Generated by Django 3.2.9 on 2021-12-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='address',
        ),
    ]
